import {
  AreaChartIcon,
  BookIcon,
  BotIcon,
  BoxSelectIcon,
  CloudIcon,
  CodeIcon,
  DatabaseIcon,
  FileHeartIcon,
  FileTextIcon,
  FlaskConicalIcon,
  HardDriveIcon,
  ImageIcon,
  KeyIcon,
  LibraryIcon,
  LightbulbIcon,
  MailIcon,
  PackageOpenIcon,
  PaintbrushIcon,
  PanelTopIcon,
  PencilRuler,
  PresentationIcon,
  RocketIcon,
  RssIcon,
  ScanSearchIcon,
  ServerIcon,
  ShellIcon,
  TypeIcon,
  Unlink2Icon,
  ZapIcon
} from 'lucide-react'

export const CATEGORIES = [
  { nombre: 'Accessibility', slug: 'accessibility', icon: LightbulbIcon },
  { nombre: 'AI', slug: 'ai', icon: BotIcon },
  { nombre: 'Analytics', slug: 'analytics', icon: AreaChartIcon },
  { nombre: 'Animation', slug: 'animation', icon: ShellIcon },
  { nombre: 'Authentication', slug: 'authentication', icon: KeyIcon },
  { nombre: 'Books', slug: 'books', icon: BookIcon },
  { nombre: 'Cloud', slug: 'cloud', icon: CloudIcon },
  { nombre: 'Database', slug: 'database', icon: DatabaseIcon },
  { nombre: 'Design', slug: 'design', icon: PaintbrushIcon },
  { nombre: 'Documentation', slug: 'documentation', icon: FileTextIcon },
  { nombre: 'Domain', slug: 'domain', icon: Unlink2Icon },
  { nombre: 'Email', slug: 'email', icon: MailIcon },
  { nombre: 'Font', slug: 'font', icon: TypeIcon },
  { nombre: 'Hosting', slug: 'hosting', icon: ServerIcon },
  { nombre: 'Icon', slug: 'icon', icon: BoxSelectIcon },
  { nombre: 'Illustration', slug: 'illustration', icon: ImageIcon },
  { nombre: 'Inspiration', slug: 'inspiration', icon: LightbulbIcon },
  { nombre: 'Library', slug: 'library', icon: LibraryIcon },
  { nombre: 'Newsletter', slug: 'newsletter', icon: RssIcon },
  { nombre: 'Open Source', slug: 'open-source', icon: CodeIcon },
  { nombre: 'Performance', slug: 'performance', icon: RocketIcon },
  { nombre: 'Portfolio', slug: 'portfolio', icon: PanelTopIcon },
  { nombre: 'Productivity', slug: 'productivity', icon: ZapIcon },
  { nombre: 'Scraping', slug: 'scraping', icon: ScanSearchIcon },
  { nombre: 'Storage', slug: 'storage', icon: HardDriveIcon },
  { nombre: 'Testing', slug: 'testing', icon: FlaskConicalIcon },
  { nombre: 'Tool', slug: 'tool', icon: PencilRuler },
  { nombre: 'UI', slug: 'ui', icon: FileHeartIcon },
  { nombre: 'CMS', slug: 'cms', icon: PackageOpenIcon },
  { nombre: 'Course', slug: 'course', icon: PresentationIcon }
]
