export const SLUG_ICONS = [
  { slug: 'accessibility', icon: '👀' },
  { slug: 'ai', icon: '🤖' },
  { slug: 'analytics', icon: '📈' },
  { slug: 'animation', icon: '🎞️' },
  { slug: 'authentication', icon: '🔐' },
  { slug: 'books', icon: '📚' },
  { slug: 'cloud', icon: '☁️' },
  { slug: 'database', icon: '💾' },
  { slug: 'design', icon: '🎨' },
  { slug: 'documentation', icon: '📖' },
  { slug: 'domain', icon: '🔗' },
  { slug: 'email', icon: '📧' },
  { slug: 'font', icon: '🔠' },
  { slug: 'hosting', icon: '📡' },
  { slug: 'icon', icon: '🖼️' },
  { slug: 'illustration', icon: '🎨' },
  { slug: 'inspiration', icon: '💡' },
  { slug: 'library', icon: '🏛️' },
  { slug: 'newsletter', icon: '📰' },
  { slug: 'open-source', icon: '🆓' },
  { slug: 'performance', icon: '🚀' },
  { slug: 'portfolio', icon: '💼' },
  { slug: 'productivity', icon: '⚙️' },
  { slug: 'scraping', icon: '🔎' },
  { slug: 'storage', icon: '📦' },
  { slug: 'testing', icon: '🧪' },
  { slug: 'tool', icon: '🛠️' },
  { slug: 'ui', icon: '🖥️' },
  { slug: 'cms', icon: '🗂️' },
  { slug: 'course', icon: '🎓' }
]
