import {
  AreaChartIcon,
  BookIcon,
  BotIcon,
  BoxSelectIcon,
  CloudIcon,
  CodeIcon,
  DatabaseIcon,
  FileHeartIcon,
  FileTextIcon,
  FlaskConicalIcon,
  HardDriveIcon,
  ImageIcon,
  KeyIcon,
  LibraryIcon,
  LightbulbIcon,
  MailIcon,
  PackageOpenIcon,
  PaintbrushIcon,
  PanelTopIcon,
  PencilRuler,
  PresentationIcon,
  RocketIcon,
  RssIcon,
  ScanSearchIcon,
  ServerIcon,
  ShellIcon,
  TypeIcon,
  Unlink2Icon,
  ZapIcon
} from 'lucide-react'

export const SLUG_ICONS = [
  { slug: 'accessibility', icon: LightbulbIcon },
  { slug: 'ai', icon: BotIcon },
  { slug: 'analytics', icon: AreaChartIcon },
  { slug: 'animation', icon: ShellIcon },
  { slug: 'authentication', icon: KeyIcon },
  { slug: 'books', icon: BookIcon },
  { slug: 'cloud', icon: CloudIcon },
  { slug: 'database', icon: DatabaseIcon },
  { slug: 'design', icon: PaintbrushIcon },
  { slug: 'documentation', icon: FileTextIcon },
  { slug: 'domain', icon: Unlink2Icon },
  { slug: 'email', icon: MailIcon },
  { slug: 'font', icon: TypeIcon },
  { slug: 'hosting', icon: ServerIcon },
  { slug: 'icon', icon: BoxSelectIcon },
  { slug: 'illustration', icon: ImageIcon },
  { slug: 'inspiration', icon: LightbulbIcon },
  { slug: 'library', icon: LibraryIcon },
  { slug: 'newsletter', icon: RssIcon },
  { slug: 'open-source', icon: CodeIcon },
  { slug: 'performance', icon: RocketIcon },
  { slug: 'portfolio', icon: PanelTopIcon },
  { slug: 'productivity', icon: ZapIcon },
  { slug: 'scraping', icon: ScanSearchIcon },
  { slug: 'storage', icon: HardDriveIcon },
  { slug: 'testing', icon: FlaskConicalIcon },
  { slug: 'tool', icon: PencilRuler },
  { slug: 'ui', icon: FileHeartIcon },
  { slug: 'cms', icon: PackageOpenIcon },
  { slug: 'course', icon: PresentationIcon }
]
